# Generated by Django 4.0.10 on 2023-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_name',
            field=models.CharField(default='no team name', max_length=255, verbose_name='Team Name'),
            preserve_default=False,
        ),
    ]
